In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import datetime as dt

In [2]:
data = pd.read_json(r'my_spotify_data(2)\MyData\endsong_0.json')
id1 = data.shape[0]

In [3]:
data2 = pd.read_json(r'C:\Users\LEBEND\Downloads\my_spotify_data(2)\MyData\endsong_1.json')
id2 = data2.shape[0]

In [4]:
id2 = id1 + id2
data2.index = range(id1, id2)

In [5]:
data = pd.concat([data, data2])

In [6]:
data['ts'] = pd.to_datetime(data['ts'], infer_datetime_format=True)
data['date'] = [d.date() for d in data['ts']]
data['time'] = [d.time() for d in data['ts']]
data['day_of_week'] = [d.day_name() for d in data['ts']]

In [7]:
na_ind = list(data[data['master_metadata_track_name'].isna()].index)

In [8]:
data.drop(na_ind, inplace=True)

In [9]:
data.describe()

          ms_played       skipped  offline_timestamp
count  3.005800e+04  11313.000000       3.005800e+04
mean   1.337048e+05      0.545832       1.016097e+12
std    1.312614e+05      0.497917       7.942234e+11
min    0.000000e+00      0.000000       0.000000e+00
25%    1.690325e+04      0.000000       1.676412e+09
50%    1.179505e+05      1.000000       1.621384e+12
75%    2.108000e+05      1.000000       1.645117e+12
max    2.503815e+06      1.000000       1.665791e+12

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 30058 entries, 0 to 30061
Data columns (total 24 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   ts                                 30058 non-null  datetime64[ns]
 1   username                           30058 non-null  object
 2   platform                           30058 non-null  object
 3   ms_played                          30058 non-null  int64
 4   conn_country                       30058 non-null  object
 5   ip_addr_decrypted                  30058 non-null  object
 6   user_agent_decrypted               30030 non-null  object
 7   master_metadata_track_name         30058 non-null  object
 8   master_metadata_album_artist_name  30058 non-null  object
 9   master_metadata_album_album_name   30058 non-null  object
 10  spotify_track_uri                  30058 non-null  object
 11  episode_name                       0 non-null      object
 12  episode_show_name                  0 non-null      object
 13  spotify_episode_uri                0 non-null      object
 14  reason_start                       30058 non-null  object
 15  reason_end                         30058 non-null  object
 16  shuffle                            30058 non-null  bool
 17  skipped                            11313 non-null  float64
 18  offline                            30058 non-null  bool
 19  offline_timestamp                  30058 non-null  int64
 20  incognito_mode                     30058 non-null  bool
 21  date                               30058 non-null  object
 22  time                               30058 non-null  object
 23  day_of_week                        30058 non-null  object
dtypes: bool(3), datetime64[ns](1), float64(1), int64(2), object(17)
memory usage: 5.1+ MB

# 1)	List of favorite artists based on
## a.	Total number of songs listened to
## b.	Total listening time of the artist
## c.	Number of times songs of the artist have been played

In [11]:
tot_artist_overall = data['master_metadata_album_artist_name'].unique()
artist_listentime_overall = list()
artist_totsongs_overall = list()
artist_songsplayed_overall = list()

# tot_artist_overall contains the list of all the artists listened to till now
# artist_listentime_overall is total listening time for an artist 
# artist_totsongs_overall is the total number of songs played by an artist doesn't include duplicates
# artist_songsplayed_overall is similar but includes duplicates too

In [12]:
for i in range(0, len(tot_artist_overall)):
    temp = data[data['master_metadata_album_artist_name'] == tot_artist_overall[i]]
    artist_listentime_overall.append(temp['ms_played'].sum())
    artist_totsongs_overall.append(temp['master_metadata_track_name'].unique().shape[0])
    artist_songsplayed_overall.append(temp.shape[0])

In [13]:
df = pd.DataFrame(list(zip(tot_artist_overall, artist_listentime_overall, artist_totsongs_overall, artist_songsplayed_overall)), columns=['Artist', 'Total_listening_time_in_ms', 'Total_no_of_songs_listened', 'No_of_times_played'])

In [14]:
df_favartist_listeningtime = df.sort_values(by=['Total_listening_time_in_ms'], ascending=False).drop(['Total_no_of_songs_listened', 'No_of_times_played'], axis=1).iloc[:50]
df_favartist_listeningtime.index = range(0, 50)

In [15]:
df_favartist_listeningtime.iloc[:50]

                  Artist  Total_listening_time_in_ms
0                  Queen                   946062945
1            The Beatles                   795533459
2            Hans Zimmer                   337189628
3             Elton John                   217035599
4        Freddie Mercury                   149117027
5       Ludwig Göransson                   101665659
6                 Pritam                    89130010
7            John Lennon                    75166582
8          Epic Mountain                    59569755
9           Amit Trivedi                    50891333
10    Shankar-Ehsaan-Loy                    49572207
11       Stephen Sanchez                    42143180
12                  ABBA                    41739951
13           A.R. Rahman                    38610730
14     Johann Strauss II                    33164933
15     Rex Orange County                    31994916
16             Radiohead                    31750030
17     Jóhann Jóhannsson                    25240967
18         Taron Egerton                    24151489
19                   AJR                    23695872
20     Michael Giacchino                    22428846
21       Frédéric Chopin                    20894119
22                Achint                    20613516
23        Paul McCartney                    19107410
24         Guns N' Roses                    18954530
25         John Williams                    18218015
26           John Denver                    17724310
27      Nicholas Britell                    17504459
28        Franz Schubert                    16399511
29          Danny Elfman                    16349841
30     Alexandre Desplat                    15770310
31           Franz Liszt                    15382911
32            Thom Yorke                    15285881
33                  Muse                    13766990
34         Frank Sinatra                    13613320
35     Simon & Garfunkel                    13122748
36   Two Steps from Hell                    13098181
37              Coldplay                    12953194
38        George Michael                    12321323
39    Patrik Pietschmann                    12239624
40            Sonu Nigam                    11876436
41           David Bowie                    11635360
42      Abhay Jodhpurkar                    11615644
43             Ajay-Atul                    11574890
44        Alan Silvestri                    11362184
45  Ludwig van Beethoven                    11098989
46        Rachel Portman                    11083823
47       Imagine Dragons                    10666730
48         Sandeep Khare                    10101305
49        Tusshar Mallek                     9319609

In [16]:
df_favartist_totsongsplayed = df.sort_values(by=['Total_no_of_songs_listened'], ascending=False).drop(['Total_listening_time_in_ms', 'No_of_times_played'], axis=1).iloc[:50]
df_favartist_totsongsplayed.index = range(0, 50)

In [17]:
df_favartist_totsongsplayed.iloc[:50]

                          Artist  Total_no_of_songs_listened
0                    The Beatles                         484
1                          Queen                         307
2                     Elton John                         159
3                    Hans Zimmer                         131
4                    John Lennon                          86
5                           ABBA                          72
6                Freddie Mercury                          63
7                         Pritam                          62
8              Michael Giacchino                          56
9                      Radiohead                          50
10             Alexandre Desplat                          42
11                 Epic Mountain                          35
12                 John Williams                          34
13                  Danny Elfman                          34
14           Two Steps from Hell                          33
15                Paul McCartney                          32
16             Simon & Garfunkel                          31
17                Alan Silvestri                          29
18             Jóhann Jóhannsson                          27
19                   A.R. Rahman                          26
20                  Lind Erebros                          26
21          Ludwig van Beethoven                          24
22               Frédéric Chopin                          24
23             Rex Orange County                          24
24            Shankar-Ehsaan-Loy                          24
25                 Ramin Djawadi                          22
26                      Bee Gees                          21
27                   David Bowie                          21
28                 Kishore Kumar                          20
29                 Taron Egerton                          20
30                Franz Schubert                          20
31              Ludwig Göransson                          19
32                           AJR                          19
33               Stephen Sanchez                          18
34                  Led Zeppelin                          17
35  Royal Philharmonic Orchestra                          16
36          Matchstick Piano Man                          15
37                George Michael                          14
38                    Thom Yorke                          14
39                   John Denver                          12
40                  Amit Trivedi                          12
41                          Muse                          12
42                 Frank Sinatra                          12
43                  James Horner                          11
44                 Thomas Newman                          11
45               Imagine Dragons                          11
46           James Newton Howard                          11
47                   Simran Hora                          11
48                     Ajay-Atul                          11
49               John D. Boswell                          11

In [18]:
df_favartist_timesplayed = df.sort_values(by=['No_of_times_played'], ascending=False).drop(['Total_listening_time_in_ms', 'Total_no_of_songs_listened'], axis=1).iloc[:50]
df_favartist_timesplayed.index = range(0, 50)

In [19]:
df_favartist_timesplayed.iloc[:50]

                 Artist  No_of_times_played
0           The Beatles                7687
1                 Queen                7382
2           Hans Zimmer                1655
3            Elton John                1519
4       Freddie Mercury                 983
5      Ludwig Göransson                 605
6           John Lennon                 592
7                Pritam                 471
8                  ABBA                 323
9     Jóhann Jóhannsson                 292
10      Stephen Sanchez                 290
11         Amit Trivedi                 286
12   Shankar-Ehsaan-Loy                 251
13        Epic Mountain                 251
14    Michael Giacchino                 240
15            Radiohead                 229
16     Nicholas Britell                 195
17       Paul McCartney                 186
18                  AJR                 181
19          A.R. Rahman                 170
20    Rex Orange County                 170
21    Alexandre Desplat                 157
22         Danny Elfman                 156
23        Taron Egerton                 154
24               Achint                 152
25    Simon & Garfunkel                 133
26        John Williams                 120
27          John Denver                 105
28           Thom Yorke                 101
29       Rachel Portman                 100
30  Two Steps from Hell                  98
31       Alan Silvestri                  98
32      John D. Boswell                  97
33    Johann Strauss II                  97
34       Tusshar Mallek                  95
35      Frédéric Chopin                  93
36      Imagine Dragons                  91
37       Franz Schubert                  88
38             Bee Gees                  86
39          David Bowie                  81
40                 Muse                  78
41        Guns N' Roses                  76
42       George Michael                  73
43             Coldplay                  70
44          Franz Liszt                  68
45        Frank Sinatra                  68
46           Sonu Nigam                  58
47            Ajay-Atul                  57
48         Arijit Singh                  56
49        Kishore Kumar                  53

# 2)	List of favorite songs based on
## a.	Number of times the songs have been played
## b.	Total listening time of the songs

In [20]:
tot_songs_overall = data['master_metadata_track_name'].unique()
songs_listentime_overall = list()
songs_timesplayed_overall = list()

# tot_songs_overall contains the list of all the songs that have been played till now
# songs_listentime_overall is total listening time for each songs
# songs_timesplayed_overall is the total number of times each songs has been played

In [21]:
for i in range(0, len(tot_songs_overall)):
    temp = data[data['master_metadata_track_name'] == tot_songs_overall[i]]
    songs_listentime_overall.append(temp['ms_played'].sum())
    songs_timesplayed_overall.append(temp.shape[0])

In [22]:
df = pd.DataFrame(list(zip(tot_songs_overall, songs_listentime_overall, songs_timesplayed_overall)), columns=['Song', 'Total_listening_time_in_ms', 'No_of_times_played'])

In [23]:
df.head()

,Song,Total_listening_time_in_ms,No_of_times_played
0,Sgt. Pepper's Lonely Hearts Club Band - Remix,8094218,84
1,Made In Heaven - Special Edition,37908794,189
2,Murph,84688500,190
3,In Only Seven Days - Remastered 2011,6559995,81
4,The Shape Of Water,8500697,56

In [24]:
df_favsong_listeningtime = df.sort_values(by=['Total_listening_time_in_ms'], ascending=False).drop(['No_of_times_played'], axis=1).iloc[:50]
df_favsong_listeningtime.index = range(0, 50)

In [25]:
df_favsong_listeningtime.iloc[:50]

,Song,Total_listening_time_in_ms
0,Murph,84688500
1,Stay,53999642
2,Somebody To Love - Remastered 2011,52568467
3,Bohemian Rhapsody - Remastered 2011,48004156
4,Across The Universe - 2021 Mix,41922541
5,Made In Heaven - Special Edition,37908794
6,It's A Hard Life - Remastered 2011,37330629
7,Don't Stop Me Now - Remastered 2011,35181463
8,Love Of My Life - Remastered 2011,33323519
9,Don't Stop Me Now - ...Revisited,33229772
10,Love Me Like There's No Tomorrow - Special Edi...,31155319
11,Spread Your Wings - Remastered 2011,31123471
12,The Prophet's Song - Remastered 2011,30975771
13,Strawberry Fields Forever - Stereo Mix 2015,29551093
14,I Am The Walrus,29193955
15,Save Me - Remastered 2011,29015540
16,In My Defence - 2000 Remix,27313143
17,Goodbye Yellow Brick Road - Remastered,25622253
18,Immune System 2,25207150
19,Under Pressure - Remastered 2011,24900933
20,Yesterday - Remastered 2009,23973832
21,S.T.A.Y.,23761155
22,THE PROTAGONIST,23417419
23,Good Company - Remastered 2011,22940242
24,Supermarine,22786838
25,Something - 2019 Mix,22446587
26,Your Song - Remastered,21871930
27,"All Dead, All Dead - Remastered 2011",21079952
28,POSTERITY,20700305
29,Don't Let The Sun Go Down On Me,20595301
30,Another One Bites The Dust - Remastered 2011,19408028
31,No Surprises - Remastered,19115476
32,The March Of The Black Queen - Remastered 2011,19091265
33,Sweet Child O' Mine,18718828
34,WINDMILLS,18320451
35,The Electro Suite,18309354
36,Crocodile Rock - Remastered,18268069
37,Pluto Projector,17716913
38,I Want To Break Free - Single Remix,17283919
39,Man On The Prowl - Remastered 2011,17097941
40,My Melancholy Blues - Remastered 2011,17042405
41,A Simple Man,16735978
42,A Kind Of Magic - Remastered 2011,16514278
43,Noor E Khuda,16162951
44,The Millionaire Waltz - Remastered 2011,16054747
45,"The Blue Danube Waltz, Op. 314",15895216
46,"Main Ki Karaan? (From ""Laal Singh Chaddha"")",15739273
47,FOILS,15383347
48,The Golden Boy - New Orchestrated Version,15293720
49,Who Needs You - Remastered 2011,15035751

In [26]:
df_favsong_timesplayed = df.sort_values(by=['No_of_times_played'], ascending=False).drop(['Total_listening_time_in_ms'], axis=1).iloc[:50]
df_favsong_timesplayed.index = range(0, 50)

In [27]:
df_favsong_timesplayed.iloc[:50]

                                                 Song  No_of_times_played
0                   Love Of My Life - Remastered 2011                 249
1                  Somebody To Love - Remastered 2011                 240
2                 Don't Stop Me Now - Remastered 2011                 232
3                         Yesterday - Remastered 2009                 225
4                 Bohemian Rhapsody - Remastered 2011                 223
5                  It's A Hard Life - Remastered 2011                 216
6                      Across The Universe - 2021 Mix                 196
7   Love Me Like There's No Tomorrow - Special Edi...                 192
8                                               Murph                 190
9                    Made In Heaven - Special Edition                 189
10                                               Stay                 189
11                Spread Your Wings - Remastered 2011                 188
12                   Don't Stop Me Now - ...Revisited                 184
13                          Save Me - Remastered 2011                 183
14                         In My Defence - 2000 Remix                 168
15             Goodbye Yellow Brick Road - Remastered                 162
16        Strawberry Fields Forever - Stereo Mix 2015                 158
17                               Something - 2019 Mix                 153
18             I Was Born To Love You - 2011 Remaster                 149
19       Another One Bites The Dust - Remastered 2011                 147
20                     Good Company - Remastered 2011                 144
21               All Dead, All Dead - Remastered 2011                 140
22                 Man On The Prowl - Remastered 2011                 138
23              My Melancholy Blues - Remastered 2011                 137
24                                    I Am The Walrus                 134
25                             Your Song - Remastered                 134
26   Crazy Little Thing Called Love - Remastered 2011                 131
27                I Want To Break Free - Single Remix                 127
28                        Nevermore - Remastered 2011                 123
29                            I'm So Tired - 2018 Mix                 123
30  Norwegian Wood (This Bird Has Flown) - Remaste...                 121
31                            Help! - Remastered 2009                 119
32                                    THE PROTAGONIST                 117
33               Seaside Rendezvous - Remastered 2011                 115
34                   Under Pressure - Remastered 2011                 113
35                        Crocodile Rock - Remastered                 112
36                         Jealousy - Remastered 2011                 111
37     Good Old-Fashioned Lover Boy - Remastered 2011                 111
38                  The Inner Light - Remastered 2009                 109
39              Rock And Roll Music - Remastered 2009                 108
40                     Killer Queen - Remastered 2011                 108
41                                              FOILS                 106
42  Is This The World We Created...? - Remastered ...                 106
43                    Don't Let The Sun Go Down On Me                 106
44            The Millionaire Waltz - Remastered 2011                 103
45     The March Of The Black Queen - Remastered 2011                 102
46               Logic Waltz In B Major - Bonus Track                 102
47             The Fool On The Hill - Remastered 2009                 100
48                   Dreamer's Ball - Remastered 2011                  99
49                                          POSTERITY                  98

# 3)	List of favorite albums based on
## a.	Total listening time of the album
## b.	Number of times songs from the album have been played

In [28]:
tot_albums_overall = data['master_metadata_album_album_name'].unique()
albums_listentime_overall = list()
albums_timesplayed_overall = list()

# tot_albums_overall contains the list of all the albums from which songs have been played till now
# albums_listentime_overall is total listening time for each album
# albums_timesplayed_overall is the total number of times any song from the album has been played

In [29]:
for i in range(0, len(tot_albums_overall)):
    temp = data[data['master_metadata_album_album_name'] == tot_albums_overall[i]]
    albums_listentime_overall.append(temp['ms_played'].sum())
    albums_timesplayed_overall.append(temp.shape[0])

In [30]:
df = pd.DataFrame(list(zip(tot_albums_overall, albums_listentime_overall, albums_timesplayed_overall)), columns=['Album', 'Total_listening_time_in_ms', 'No_of_times_played'])

In [31]:
df_favalbum_listeningtime = df.sort_values(by=['Total_listening_time_in_ms'], ascending=False).drop(['No_of_times_played'], axis=1).iloc[:50]
df_favalbum_listeningtime.index = range(0, 50)

In [32]:
df_favalbum_listeningtime.iloc[:50]

,Album,Total_listening_time_in_ms
0,Interstellar (Original Motion Picture Soundtrack),211578416
1,A Night At The Opera,171290590
2,Diamonds,161263338
3,The Beatles,153824210
4,Sgt. Pepper's Lonely Hearts Club Band,119898192
5,A Day At The Races,116410910
6,The Works,107431566
7,Tenet (Original Motion Picture Soundtrack),101446545
8,News Of The World,97154507
9,Let It Be,87743972
10,Jazz,77532039
11,Abbey Road,76976183
12,The Game,75297735
13,Never Boring,71345611
14,Help!,59304171
15,Love,49423699
16,Inception,45384589
17,Queen II,42883975
18,Hot Space,42678565
19,Made In Heaven,42025532
20,Bohemian Rhapsody,41069835
21,Revolver,40383663
22,Beatles For Sale,38717102
23,Imagine,36409295
24,Mr Bad Guy,35305344
25,A Kind Of Magic,33960161
26,Rubber Soul,33915608
27,Qala,32091981
28,A Hard Day's Night,30749899
29,Barcelona,30673998
30,Sheer Heart Attack,29458400
31,The Miracle,28062125
32,Dunkirk (Original Motion Picture Soundtrack),26537154
33,The Theory of Everything (Original Motion Pict...,25240967
34,Magical Mystery Tour,24717874
35,Rocketman,24330050
36,Immune System 2,23397932
37,OK ORCHESTRA,23332182
38,The Amazing Spider-Man 2 (The Original Motion ...,22799527
39,Innuendo,21750660
40,Scam 1992 (Original Score),20611706
41,Anthology 2,20054237
42,OK Computer OKNOTOK 1997 2017,19545679
43,Caribou,19535320
44,My Name Is Khan (Original Motion Picture Sound...,19257777
45,Appetite For Destruction,18845558
46,Andhadhun,18328958
47,Goodbye Yellow Brick Road,17974816
48,Pony,17822115
49,Don't Look Up (Soundtrack from the Netflix Film),17512199

In [33]:
df_favalbum_timesplayed = df.sort_values(by=['No_of_times_played'], ascending=False).drop(['Total_listening_time_in_ms'], axis=1).iloc[:50]
df_favalbum_timesplayed.index = range(0, 50)

In [34]:
df_favalbum_timesplayed.iloc[:50]

                                                Album  No_of_times_played
0                                         The Beatles                1367
1                                A Night At The Opera                1075
2                                            Diamonds                1070
3               Sgt. Pepper's Lonely Hearts Club Band                1050
4                                           The Works                 799
5   Interstellar (Original Motion Picture Soundtrack)                 787
6                                          Abbey Road                 747
7                                  A Day At The Races                 735
8                                               Help!                 697
9                                   News Of The World                 696
10                                               Jazz                 680
11         Tenet (Original Motion Picture Soundtrack)                 613
12                                          Let It Be                 612
13                                           The Game                 598
14                                           Revolver                 491
15                                           Queen II                 443
16                                       Never Boring                 420
17                                     Made In Heaven                 400
18                                   Beatles For Sale                 400
19                                        Rubber Soul                 384
20                                 A Hard Day's Night                 365
21                                 Sheer Heart Attack                 361
22                                               Love                 348
23                                          Inception                 346
24                                        The Miracle                 315
25                                  Bohemian Rhapsody                 313
26  The Theory of Everything (Original Motion Pict...                 292
27                                            Imagine                 264
28                                    A Kind Of Magic                 259
29                                          Hot Space                 258
30                                         Mr Bad Guy                 248
31                               Magical Mystery Tour                 245
32                                       Past Masters                 225
33                                          Barcelona                 213
34                                   Please Please Me                 213
35   Don't Look Up (Soundtrack from the Netflix Film)                 196
36                                           Innuendo                 186
37                                               Qala                 169
38                                       OK ORCHESTRA                 168
39                                          Rocketman                 157
40  Aspirants: Season 1 (Music From the TVF Origin...                 156
41                         Scam 1992 (Original Score)                 151
42                          Goodbye Yellow Brick Road                 149
43                                   With The Beatles                 146
44       Dunkirk (Original Motion Picture Soundtrack)                 142
45                                    Easy On My Eyes                 139
46        Doctor Strange in the Multiverse of Madness                 136
47                                              Queen                 134
48                                 The Shape Of Water                 134
49                                        Anthology 2                 133

# 4) Total listening time, total number of songs listened to, total number of artists listened to, total number of albums listened to

In [35]:
tot_listening_time = data['ms_played'].sum()/60000
print(f'Total listening time in minutes is : {tot_listening_time}')
print(f'Total number of songs listened to is : {len(tot_songs_overall)}')
print(f'Total number of artists listened to is : {len(tot_artist_overall)}')
print(f'Total number of albums listened to is : {len(tot_albums_overall)}')

Total listening time in minutes is : 66981.63295
Total number of songs listened to is : 3159
Total number of artists listened to is : 544
Total number of albums listened to is : 1075

# 5)	Favorite time of the day for listening based on
## a.	Total number of songs listened to
## b.	Total listening time

In [36]:
morn = [dt.time(6, 0, 0), dt.time(11, 59, 59)]
afnoon = [dt.time(12, 0, 0), dt.time(17, 59, 59)]
eve = [dt.time(18, 0, 0), dt.time(23, 59, 59)]
night = [dt.time(0, 0, 0), dt.time(5, 59, 59)]
time_of_day = [morn, afnoon, eve, night]
time_of_day_listentime = list()
time_of_day_songsplayed = list()
td = ['Morning', 'Afternoon', 'Evening', 'Night']

In [37]:
for i in range(0,4):
    temp = data[[d >= time_of_day[i][0] and d <= time_of_day[i][1] for d in data['time']]]
    time_of_day_songsplayed.append(temp.shape[0])
    time_of_day_listentime.append(temp['ms_played'].sum())

In [38]:
df = pd.DataFrame(list(zip(td, time_of_day_listentime, time_of_day_songsplayed)), columns=['Time_of_day', 'Total_listening_time_in_ms', 'Total_songs_listened_to'])

In [39]:
df_favtime_msplayed = df.sort_values(by=['Total_listening_time_in_ms'], ascending=False).drop(['Total_songs_listened_to'], axis=1)
df_favtime_msplayed.index = range(0, 4)

In [40]:
df_favtime_msplayed

  Time_of_day  Total_listening_time_in_ms
0     Evening                  1523774566
1   Afternoon                  1365279716
2     Morning                   798619120
3       Night                   331224575

In [41]:
df_favtime_songsplayed = df.sort_values(by=['Total_songs_listened_to'], ascending=False).drop(['Total_listening_time_in_ms'], axis=1)
df_favtime_songsplayed.index = range(0, 4)

In [42]:
df_favtime_songsplayed

  Time_of_day  Total_songs_listened_to
0   Afternoon                    11056
1     Evening                    10495
2     Morning                     6285
3       Night                     2222

# 6)	Favorite artist for each time of the day based on
## a.	Total number of songs listened to
## b.	Total listening time

In [43]:
timeofday_artist_time = [['nothing', 0], ['nothing', 0], ['nothing', 0], ['nothing', 0]]
timeofday_artist_songsplayed = [['nothing', 0], ['nothing', 0], ['nothing', 0], ['nothing', 0]]

In [44]:
for i in range(0,4):
    temp = data[[d >= time_of_day[i][0] and d <= time_of_day[i][1] for d in data['time']]]
    temp_art = temp['master_metadata_album_artist_name'].unique()
    for j in temp_art:
        temp2 = temp[temp['master_metadata_album_artist_name'] == j]
        if temp2.shape[0] > timeofday_artist_songsplayed[i][1]:
            timeofday_artist_songsplayed[i][0] = j
            timeofday_artist_songsplayed[i][1] = temp2.shape[0]
        if temp2['ms_played'].sum() > timeofday_artist_time[i][1]:
            timeofday_artist_time[i][0] = j
            timeofday_artist_time[i][1] = temp2['ms_played'].sum()

In [45]:
df_timeofday_artist_tottime = pd.DataFrame(timeofday_artist_time, columns=['Artist', 'Total_time_listened_in_ms'])
df_timeofday_artist_tottime.insert(loc=0, column='Time_of_day', value=td)

In [46]:
df_timeofday_artist_tottime

  Time_of_day       Artist  Total_time_listened_in_ms
0     Morning        Queen                  271071626
1   Afternoon        Queen                  378970478
2     Evening  The Beatles                  340981097
3       Night        Queen                   74101608

In [47]:
df_timeofday_artist_songsplayed = pd.DataFrame(timeofday_artist_songsplayed, columns=['Artist', 'Total_songs_played'])
df_timeofday_artist_songsplayed.insert(loc=0, column='Time_of_day', value=td)

In [48]:
df_timeofday_artist_songsplayed

  Time_of_day       Artist  Total_songs_played
0     Morning        Queen                2200
1   Afternoon        Queen                3169
2     Evening  The Beatles                2836
3       Night  The Beatles                 609

# 7)	Favorite song for each time of the day based on
## a.	Total number of songs listened to
## b.	Total listening time

In [49]:
timeofday_song_time = [['nothing', 0], ['nothing', 0], ['nothing', 0], ['nothing', 0]]
timeofday_song_songsplayed = [['nothing', 0], ['nothing', 0], ['nothing', 0], ['nothing', 0]]

In [50]:
for i in range(0,4):
    temp = data[[d >= time_of_day[i][0] and d <= time_of_day[i][1] for d in data['time']]]
    temp_art = temp['master_metadata_track_name'].unique()
    for j in temp_art:
        temp2 = temp[temp['master_metadata_track_name'] == j]
        if temp2.shape[0] > timeofday_song_songsplayed[i][1]:
            timeofday_song_songsplayed[i][0] = j
            timeofday_song_songsplayed[i][1] = temp2.shape[0]
        if temp2['ms_played'].sum() > timeofday_song_time[i][1]:
            timeofday_song_time[i][0] = j
            timeofday_song_time[i][1] = temp2['ms_played'].sum()

In [51]:
df_timeofday_song_tottime = pd.DataFrame(timeofday_song_time, columns=['Song', 'Total_time_listened_in_ms'])
df_timeofday_song_tottime.insert(loc=0, column='Time_of_day', value=td)

In [52]:
df_timeofday_song_tottime

  Time_of_day                                Song  Total_time_listened_in_ms
0     Morning                               Murph                   20248281
1   Afternoon  Somebody To Love - Remastered 2011                   26488166
2     Evening                               Murph                   35432958
3       Night                               Murph                    8605153

In [53]:
df_timeofday_song_songsplayed = pd.DataFrame(timeofday_song_songsplayed, columns=['Song', 'Total_times_played'])
df_timeofday_song_songsplayed.insert(loc=0, column='Time_of_day', value=td)

In [54]:
df_timeofday_song_songsplayed

  Time_of_day                                 Song  Total_times_played
0     Morning  Don't Stop Me Now - Remastered 2011                  85
1   Afternoon   Somebody To Love - Remastered 2011                 132
2     Evening          Yesterday - Remastered 2009                  91
3       Night          Yesterday - Remastered 2009                  33

# 8)	Favorite day of the week for listening songs based on
## a.	Total number of songs listened to
## b.	Total listening time

In [55]:
weekdays = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
favday_listentime = list()
favday_songsplayed = list()
for i in weekdays:
    temp = data[data['day_of_week'] == i]
    favday_listentime.append(temp['ms_played'].sum())
    favday_songsplayed.append(temp.shape[0])

In [56]:
df = pd.DataFrame(list(zip(weekdays, favday_listentime, favday_songsplayed)), columns=['Day_of_the_week', 'Total_listening_time_in_ms', 'Total_songs_listened_to'])

In [57]:
df_favday_msplayed = df.sort_values(by=['Total_listening_time_in_ms'], ascending=False).drop(['Total_songs_listened_to'], axis=1)
df_favday_msplayed.index = range(0, 7)

In [58]:
df_favday_msplayed

  Day_of_the_week  Total_listening_time_in_ms
0       Wednesday                   608612966
1          Monday                   590375733
2          Sunday                   587195975
3        Saturday                   582328563
4          Friday                   577050842
5        Thursday                   541830257
6         Tuesday                   531503641

In [59]:
df_favday_songsplayed = df.sort_values(by=['Total_songs_listened_to'], ascending=False).drop(['Total_listening_time_in_ms'], axis=1)
df_favday_songsplayed.index = range(0, 7)

In [60]:
df_favday_songsplayed

  Day_of_the_week  Total_songs_listened_to
0       Wednesday                     4391
1          Monday                     4372
2          Friday                     4341
3          Sunday                     4339
4        Saturday                     4322
5         Tuesday                     4235
6        Thursday                     4058

# 9)	Songs that were most repeated in a single day

In [61]:
dates_unique = data['date'].unique()
most_played_day = list()
for i in range(0,len(dates_unique)):
    most_played_day.append(['nothing', 0])

In [62]:
for i in range(0,len(dates_unique)):
    temp = data[data['date'] == dates_unique[i]]
    temp_songs = temp['master_metadata_track_name'].unique()
    for j in temp_songs:
        temp2 = temp[temp['master_metadata_track_name'] == j]
        if temp2.shape[0] > most_played_day[i][1]:
            most_played_day[i][0] = j
            most_played_day[i][1] = temp2.shape[0]

In [63]:
df = pd.DataFrame(most_played_day, columns=['Name_of_song', 'No_of_times_played'])
df.insert(loc=0, column='Date', value=dates_unique)

In [64]:
df_most_played_singleday = df.sort_values(by=['No_of_times_played'], ascending=False).iloc[:50]
df_most_played_singleday.index = range(0, 50)

In [65]:
df_most_played_singleday.iloc[:50]

,Date,Name_of_song,No_of_times_played
0,2022-11-19,You Know You Belong To Me,51
1,2023-04-09,Grow Old With Me - Ultimate Mix,46
2,2021-12-21,Peter Parker Picked a Perilously Precarious Pr...,34
3,2022-10-08,Wedding Vows (Bonus Track),34
4,2022-10-21,Logic Waltz In B Major - Bonus Track,33
5,2023-01-26,Evangeline,32
6,2021-05-06,"All Dead, All Dead - Remastered 2011",32
7,2022-11-07,I'm So Tired - 2018 Mix,31
8,2023-04-08,Love - Ultimate Mix,30
9,2022-10-22,Logic Waltz In B Major - Bonus Track,30
10,2023-01-21,Ghodey Pe Sawaar,30
11,2022-11-22,Penny Lane - Stereo Mix 2017,29
12,2021-11-20,Suspirium,29
13,2023-02-13,Real Love - Anthology 2 Version,28
14,2022-05-25,"Main Ki Karaan? (From ""Laal Singh Chaddha"")",27
15,2022-05-26,"Main Ki Karaan? (From ""Laal Singh Chaddha"")",25
16,2021-07-15,Rocket Man (I Think It's Going To Be A Long Lo...,24
17,2022-06-02,Mere Dholna (The Sisters),24
18,2022-09-18,With A Little Help From My Friends - Remix,24
19,2021-11-01,Yesterday - Remastered 2009,23
20,2022-10-12,Strawberry Fields Forever - Stereo Mix 2015,22
21,2023-01-25,Evangeline,22
22,2023-04-10,Grow Old With Me - Ultimate Mix,21
23,2022-02-11,Epilogue,21
24,2022-03-05,Seaside Rendezvous - Remastered 2011,20
25,2022-09-10,Daydream by Design,20
26,2023-04-12,The Invisible Man - Remastered 2011,20
27,2021-08-30,Good Company - Remastered 2011,20
28,2022-01-15,Raanjhanaa,19
29,2023-04-13,No Reply - Remastered 2009,19
30,2022-11-10,Creep,19
31,2022-08-24,My Way - 2008 Remastered,19
32,2022-10-24,Logic Waltz In B Major - Bonus Track,18
33,2022-05-07,No Surprises - Remastered,18
34,2023-01-08,Who Needs You - Remastered 2011,18
35,2023-04-16,Television / So Far So Good,18
36,2022-07-18,World's Smallest Violin,18
37,2021-03-05,Love Me Like There's No Tomorrow - Special Edi...,18
38,2021-07-12,Your Song - Remastered,17
39,2021-05-04,Norwegian Wood (This Bird Has Flown) - Remaste...,17
40,2022-12-11,We Are Family Theme,17
41,2022-12-29,Blackout,17
42,2022-10-14,The Inner Light - Remastered 2009,17
43,2022-05-16,Beautiful In White,16
44,2023-02-28,Baby's In Black - Remastered 2009,16
45,2023-04-17,Rubaaiyaan,16
46,2021-10-03,Under Pressure - Remastered 2011,16
47,2022-07-17,Chalkboard,16
48,2022-01-02,Lemon Tree,16
49,2022-11-29,Night Changes,16